export default function getKeywords() {
  return [
    "Film",
    "Tamil",
    "Telugu language",
    "Movie theater",
    "Dubbing",
    "Casting",
    "Tamil cinema",
    "High-definition video",
    "Theater",
    "The Greatest of All Time",
    "Horror",
    "Malayalam",
    "Over-the-top media service",
    "Devara: Part 1",
    "CTRL",
    "Joker",
    "Film criticism",
    "Telugu cinema",
    "Maharaja",
    "The Wild Robot",
    "Stay The Night",
    "Sam and Colby",
    "Wicked",
    "Here",
    "Halloween",
    "Annaatthe",
    "AMC Theatres",
    "AMC",
    "Here",
    "Sam and Colby",
    "Stay The Night",
    "Theater",
    "The Wild Robot",
    "Pixels",
    "Wicked",
    "Lee",
    "Halloween",
    "Movie theater",
    "Maharaja",
    "Vivamax",
    "movie download",
    "movies",
    "tamil movie",
    "hindi movie",
    "new movie",
    "tamil movie download",
    "filmyzilla",
    "isaimini",
    "goat",
    "goat movie",
    "movie theater",
    "joker movie",
    "horror movie",
    "it movie",
    "moviesda",
    "ctrl",
    "tamil dubbed movie download",
    "ibomma movie",
    "ctrl movie",
    "tv movie",
    "kuttymovies",
    "devara",
    "devara movie",
    "south movie",
    "mp4moviez",
    "kavundampalayam movie",
    "movie theaters near me",
    "sam and colby movie 2024",
    "sam and colby movie",
    "movie theater",
    "movie theater near me",
    "phone booth movie",
    "here movie",
    "saturday night movie",
    "am i racist movie",
    "stay the night movie",
    "stay the night",
    "the forge movie",
    "talk to me movie",
    "out of my mind movie",
    "wild robot movie",
    "tax collector movie",
    "look back movie",
    "pixels movie",
    "maharaja",
    "the wild robot",
    "halloween movie",
    "conclave movie",
    "robot movie",
    "wicked movie",
  ];
}
