export default function getKeywords() {
  return [
    "yts mx",
    "yts torrent",
    "torrent",
    "yts movie",
    "yts download",
    "yts movies",
    "movies",
    "yts movie download",
    "yts torrent magnet",
    "deadpool",
    "deadpool yts",
    "torrent download",
    "yts series",
    "subtitles",
    "yts subtitles",
    "yify yts",
    "yify",
    "1337x",
    "yts tv",
    "yts movies download",
    "yts proxy",
    "yts downloader",
    "utorrent",
    "torrent movies",
    "pirate bay",
    "the platform 2",
    "platform 2",
    "salem's lot 2024",
    "popcornflix",
    "popcorn time",
    "demonoid",
    "thepiratebay3",
    "salem's lot",
    "trouble 2024",
    "hold your breath",
    "house of spoils",
    "hold your breath 2024",
    "arabseed",
    "x1337x",
    "yesmovies",
    "hurawatch",
    "baiscopelk",
    "psarips",
    "subscenes",
    "uts",
    "bilibili",
    "the wasp",
    "extratorrents",
    "yt1s",
    "yts studio",
    "YIFY",
    "Torrent file",
    "Subtitle",
    "The Pirate Bay",
    "Magnet URI scheme",
    "1337x",
    "Television show",
    "Deadpool & Wolverine",
    "Deadpool",
    "µTorrent",
    "Proxy server",
    "Deadpool",
    "BitTorrent",
    "123Movies",
    "RARBG",
    "Salem's Lot",
    "Vegamovies - Watch Free Movies and Download Bollywood Hollywood South Indian Movies HD",
    "The Platform 2",
    "Hold Your Breath",
    "YTA TV",
    "The Wasp",
    "The Killer's Game",
    "House of Spoils",
    "The Platform",
    "The Avengers",
    "Vegamovies - Watch Free Movies and Download Bollywood Hollywood South Indian Movies HD",
    "The Platform 2",
    "CTRL",
    "The Killer's Game",
    "YTS DOWNLOAD",
    "The Platform",
    "Hold Your Breath",
    "Salem's Lot",
    "House of Spoils",
    "Stree",
    "The Wasp",
    "'Salem's Lot",
    "Popcornflix",
    "Despicable Me 4",
    "The Avengers",
    "YTA TV",
    "Tenor",
    "yts mx",
    "torrent",
    "yts torrent",
    "yts movie",
    "yts movies",
    "yts movie download",
    "yts torrent magnet",
    "deadpool",
    "yts series",
    "yify",
    "yts proxy",
    "1337x",
    "yts official",
    "utorrent download",
    "imdb",
    "pirate bay",
    "yts app",
    "piratebay",
    "movierulz",
    "rarbg",
    "the platform 2",
    "yts.mx",
    "bilibili",
    "pirates bay",
    "the substance",
    "bilibili",
    "the substance",
    "yts unblocked",
    "imdb",
    "yts.mx",
    "yts official",
    "utorrent download",
    "yts movie download",
  ];
}
